# Apply to all files without committing:
#   pre-commit run --all-files
# Apply to changed files:
#   pre-commit run
# Update this file:
#   pre-commit autoupdate

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-toml
      # - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        name: Format code
  # NOTE: disabling mkdown formatting as it breaks some annotations that rely on line spacing
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.33.0
  #   hooks:
  #     - id: markdownlint-fix
  # args: [
  #     # Auto-generated files.
  #     --ignore=docs/user_guide/api/visualization.md,
  #     --ignore=docs/user_guide/api/LudwigModel.md,
  #   ]
#   NOTE: mdformat is incompatible with mkdocs content tabs.
#   - repo: https://github.com/executablebooks/mdformat
#     rev: 0.7.13
#     hooks:
#       - id: mdformat
#         additional_dependencies:
#           - mdformat-gfm
#           - mdformat_frontmatter
#         exclude: CHANGELOG.md
