# Project information
site_name: 'Ludwig'
site_description: 'Deep learning toolbox'
site_author: 'Piero Molino'
site_url: 'https://ludwig-ai.github.io/ludwig-docs/'

# Repository
repo_name: 'ludwig-ai/ludwig'
repo_url: 'https://github.com/ludwig-ai/ludwig'
edit_uri: 'https://github.com/ludwig-ai/ludwig-docs/edit/master/src/docs/'

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Uber Technologies Inc., 2021 Linux Foundation Data & AI'

# Navigation
nav:
  - About: 'index.md'
  - Getting Started: 'getting_started.md'
  - Examples: 'examples.md'
  - User Guide:
      - 'User Guide Intro': 'user_guide/user_guide_intro.md'
      - 'Command Line Interface': 'user_guide/command_line_interface.md'
      - 'Data Preprocessing': 'user_guide/data_preprocessing.md'
      - 'Data Postprocessing': 'user_guide/data_postprocessing.md'
      - 'Configuration':
        - 'Configuration Intro': 'configuration/configuration_intro.md'
        - 'Input Features': 'configuration/input_features.md'
        - 'Combiner': 'configuration/combiner.md'
        - 'Output Features': 'configuration/output_features.md'
        - 'Training': 'configuration/training.md'
        - 'Preprocessing': 'configuration/preprocessing.md'
        - 'Binary Features': 'configuration/binary_features.md'
        - 'Numerical Features': 'configuration/numerical_features.md'
        - 'Category Features': 'configuration/category_features.md'
        - 'Set Features': 'configuration/set_features.md'
        - 'Bag Features': 'configuration/bag_features.md'
        - 'Sequence Features': 'configuration/sequence_features.md'
        - 'Text Features': 'configuration/text_features.md'
        - 'Time Series Features': 'configuration/time_series_features.md'
        - 'Audio Features': 'configuration/audio_features.md'
        - 'Image Features': 'configuration/image_features.md'
        - 'Date Features': 'configuration/date_features.md'
        - 'H3 Features': 'configuration/h3_features.md'
        - 'Vector Features': 'configuration/vector_features.md'
        - 'Combiners': 'configuration/combiners.md'
      - 'Distributed Execution Backends': 'user_guide/distributed_execution_backends.md'
      - 'Hyper-parameter optimization': 'user_guide/hyperparameter_optimization.md'
      - 'Programmatic API': 'user_guide/programmatic_api.md'
      - 'Visualizations': 'user_guide/visualizations.md'
      - 'Serving': 'user_guide/serving.md'
      - 'Datasets': 'user_guide/datasets.md'
      - 'Integrations': 'user_guide/integrations.md'
  - Developer Guide:
      - 'Developer Guide Intro': 'developer_guide/developer_guide_intro.md'
      - 'Codebase Structure': 'developer_guide/codebase_structure.md'
      - 'Add an Encoder': 'developer_guide/add_an_encoder.md'
      - 'Add a Decoder': 'developer_guide/add_a_decoder.md'
      - 'Add a Feature Type': 'developer_guide/add_a_feature_type.md'
      - 'Hyper-parameter Optimization': 'developer_guide/hyper_parameter_optimization.md'
      - 'Add an Integration': 'developer_guide/add_an_integration.md'
      - 'Add an Dataset': 'developer_guide/add_a_dataset.md'
      - 'Style Guidelines and Tests': 'developer_guide/style_guidelines_and_tests.md'
  - API:
      - 'LudwigModel': 'api/LudwigModel.md'
      - 'Visualization': 'api/visualization.md'
  - Community: 'community.md'
  - FAQ: 'faq.md'

# Configuration
site_dir: '../docs/'
theme:
  name: 'material'
  language: 'en'
  logo: 'images/ludwig_logo.svg'
  favicon: 'favicon.ico'
  custom_dir: 'custom/'
  palette:
    scheme: 'slate'
    primary: 'grey'
    accent: 'grey'

# Customization
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/monokai.css'

#extra_javascript:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      baselevel: 2
  - codehilite:
      guess_lang: false
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_div_format
