# Project information
site_name: 'Ludwig'
site_description: 'Deep learning toolbox'
site_author: 'Piero Molino'
site_url: 'https://ludwig-ai.github.io/ludwig-docs/'

# Repository
repo_name: 'ludwig-ai/ludwig'
repo_url: 'https://github.com/ludwig-ai/ludwig'
edit_uri: edit/master/mkdocs/docs/

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Uber Technologies Inc.'

# Navigation
nav:
  - About: 'index.md'
  - Getting Started: 'getting_started.md'
  - Examples: 'examples.md'
  - User Guide: 'user_guide.md'
  - DpGuide:
      - 'Codebase Structure': 'developerguide/CodebaseStructure.md'
      - 'Adding an Encoder': 'developerguide/adding_an_encoder.md'
      - 'Add A New Decoder Class': 'developerguide/AddANewDecoderClass.md'
      - 'Add A New Feature Class': 'developerguide/add_a_new_feature_class.md'
      - 'Hyper-parameter Optimization': 'developerguide/hyper_parameter_optimization.md'
      - 'Adding a new Integration': 'developerguide/adding_a_new_integration.md'
      - 'Style Guidelines and Tests': 'developerguide/style_guidelines_and_tests'
  - Developer Guide: 'developer_guide.md'
  - API:
      - 'LudwigModel': 'api/LudwigModel.md'
      - 'Visualization': 'api/visualization.md'
  - Community: 'community.md'
  - FAQ: 'faq.md'

# Configuration
site_dir: '../docs/'
theme:
  name: 'material'
  language: 'en'
  logo: 'images/ludwig_logo.svg'
  favicon: 'favicon.ico'
  custom_dir: 'custom/'
  palette:
    scheme: 'slate'
    primary: 'grey'
    accent: 'grey'

# Customization
extra_css:
  - 'stylesheets/extra.css'
  - 'stylesheets/monokai.css'

#extra_javascript:
#  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      baselevel: 2
  - codehilite:
      guess_lang: false
#  - pymdownx.superfences:
#      custom_fences:
#        - name: mermaid
#          class: mermaid
#          format: !!python/name:pymdownx.superfences.fence_div_format
