name: Publish Docs

on:
  push:
    branches: [main]

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Linux
        if: runner.os == 'linux'
        run: |
          sudo apt-get install -y cmake libsndfile1

      - name: Install Ludwig
        run: |
          pip install ludwig
          pip install ludwig[viz]

      - name: Set Ludwig version env
        run: |
          echo "ludwig_version=$(python -c "import ludwig; print('.'.join(ludwig.__version__.split('.')[:2]))")" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.in

      - name: Setup doc deploy
        run: |
          git config --global user.name ci-bot
          git config --global user.email ci-bot@ludwig.ai

      - name: Publish docs
        run: mike deploy --push --update-aliases ${{ env.ludwig_version }} latest  --alias-type=copy --title="${{ env.ludwig_version }} (latest)"

      - name: Clean up old version titles
        run: |
          mike list | grep '(latest)' | grep -v '\[latest\]' | sed 's/.*(\(.*\)).*/\1/' | while read -r ver; do
            mike retitle --push "$ver" "$ver"
          done

      - name: Copy sitemap and robots.txt to root
        run: |
          git stash --include-untracked
          git checkout gh-pages
          cp ${{ env.ludwig_version }}/sitemap.xml sitemap.xml
          cp ${{ env.ludwig_version }}/robots.txt robots.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Copying sitemap from version to make it easy for search engines to find our documentation.
          branch: gh-pages
          push_options: --force
