name: Pull Request Verification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Setup Linux
        if: runner.os == 'linux'
        run: |
          sudo apt-get install -y cmake libsndfile1

      - name: Install Ludwig
        run: pip install ludwig[full]

      - name: Set Ludwig version env
        run: |
          echo "ludwig_version=$(python -c "import ludwig; print('.'.join(ludwig.__version__.split('.')[:2]))")" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate API Docs
        run: python code_doc_autogen.py

      - name: Validate branch clean
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Branch not clean! Auto-generated docs are out of sync with latest Ludwig release. Please run `python code_doc_autogen.py` and include those changes in a separate PR."
            exit 1
          fi
