name: Test Docs

on:
  pull_request:
    branches: ["master"]

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      - name: Upgrade Pip
        run: |
          python -m pip -U pip

      - name: Setup Linux
        run: |
          sudo apt-get install -y cmake libsndfile1

      - name: Install Ludwig
        run: |
          pip install ludwig[full]==0.7

      - name: Set Ludwig version env
        run: |
          echo "ludwig_version=$(python -c "import ludwig; print('.'.join(ludwig.__version__.split('.')[:2]))")" >> $GITHUB_ENV

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test docs
        run: mkdocs build
